// Badges.styles.tsx

import { StyleSheet, Platform, Dimensions } from 'react-native';

const CARD_MARGIN = 15;
const NUM_COLUMNS = 2;
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const CARD_WIDTH = (SCREEN_WIDTH - (NUM_COLUMNS + 1) * CARD_MARGIN) / NUM_COLUMNS;

export const COLORS = {
  primary: '#4A90E2',
  secondary: '#50E3C2',
  background: '#1E1E2E',
  cardBackground: '#1E1E2E',
  white: '#FFFFFF',
  black: '#000000',
  textPrimary: '#FFFFFF',
  textSecondary: '#B0B0C0',
  gold: '#FFD700',
  lightGray: '#E0E0E0',
  error: '#FF4D4D',
  success: '#4CAF50',
  particlesDark: '#FFFFFF', 
  badgeBackground: '#1E1E2E', 
};

const styles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  headerBlur: {
    ...StyleSheet.absoluteFillObject,
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    zIndex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 20,
    height: 100,
  },
  backButton: {
    padding: 10,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: COLORS.white,
    textAlign: 'center',
    marginVertical: 10,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  profileSection: {
    flexDirection: 'column', // Accommodate two rows
    alignItems: 'center',
    padding: 20,
    backgroundColor: COLORS.cardBackground,
    marginHorizontal: 20,
    borderRadius: 15,
    marginTop: 120,
    elevation: 8,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
    marginBottom: 20, // Space between rows
  },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 3,
    borderColor: COLORS.primary,
  },
  profileActiveDays: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginHorizontal: 10,
    flex: 1,
    textAlign: 'center',
  },
  scoreContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    borderRadius: 40,
    width: 80,
    height: 80,
    elevation: 5,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  scoreText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  pinnedBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
  },
  pinnedBadgeLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.white,
    marginRight: 10,
  },
  pinnedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pinnedBadgeImage: {
    width: 30,
    height: 30,
  },
  pinnedBadgeName: {
    fontSize: 18,
    color: COLORS.white,
    marginLeft: 10,
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.white,
    marginHorizontal: 20,
    marginTop: 30,
    marginBottom: 15,
  },
  badgeList: {
    paddingHorizontal: CARD_MARGIN / 2,
  },
  badgeContainer: {
    margin: CARD_MARGIN / 2,
    width: CARD_WIDTH,
    aspectRatio: 1,
  },
  badgeCard: {
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.badgeBackground, 
    borderRadius: 12,
    padding: 6,
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 3,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    backfaceVisibility: 'hidden',
  },
  badgeIconContainer: {
    width: '80%',
    aspectRatio: 1,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.cardBackground,
  },
  badgeImage: {
    width: '80%',
    height: '80%',
    marginVertical: -20,
  },
  badgeTitle: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    color: COLORS.white,
    marginBottom: 5,
  },
  badgeDescription: {
    fontSize: 10,
    textAlign: 'center',
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  progressSection: {
    width: '100%',
    alignItems: 'center',
  },
  progressText: {
    marginTop: 5,
    fontSize: 12,
    fontWeight: '500',
    color: COLORS.white,
  },
  lockOverlay: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255,77,77,0.8)',
    borderRadius: 20,
    padding: 8,
  },
  badgeBackCard: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.badgeBackground, // Ensure consistency
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    backfaceVisibility: 'hidden',
    transform: [{ rotateY: '180deg' }],
  },
  badgeBackTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 10,
    textAlign: 'center',
  },
  badgeDetails: {
    fontSize: 14,
    textAlign: 'center',
    color: COLORS.white,
    marginBottom: 5,
  },
  unearnedBadge: {
    opacity: 0.2,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 18,
    fontWeight: '500',
    color: COLORS.white,
  },
  badgeTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.cardBackground,
    padding: 15,
    marginHorizontal: 20,
    borderRadius: 15,
    marginBottom: 15,
    elevation: 4,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  badgeTableImage: {
    width: 60,
    height: 60,
  },
  badgeTableInfo: {
    marginLeft: 20,
    flex: 1,
  },
  badgeTableTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.white,
  },
  badgeTableDescription: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  badgeTableProgressText: {
    fontSize: 14,
    color: COLORS.white,
    marginTop: 8,
  },
});

export default styles;
