// src/screens/AppNav/Badges/Badges.styles.tsx

import { StyleSheet, Platform, Dimensions } from 'react-native';

const CARD_MARGIN = 15;
const NUM_COLUMNS = 2;
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const CARD_WIDTH =
  (SCREEN_WIDTH - (NUM_COLUMNS + 1) * CARD_MARGIN) / NUM_COLUMNS;

export const getColors = (isDarkMode: boolean) => ({
  primary: '#4A90E2',
  secondary: '#50E3C2',
  background: isDarkMode ? '#121212' : '#b8b6b6',
  cardBackground: isDarkMode ? '#1E1E1E' : '#b8b6b6',
  white: '#FFFFFF',
  black: '#000000',
  textPrimary: isDarkMode ? '#FFFFFF' : '#000000',
  textSecondary: isDarkMode ? '#B0B0C0' : '#707070',
  gold: '#FFD700',
  lightGray: '#E0E0E0',
  error: '#FF4D4D',
  success: '#4CAF50',
  particlesDark: '#39FF14',
  badgeBackground: isDarkMode ? '#1E1E2E' : '#012178',
  overlayBackground: 'rgba(0, 0, 0, 0.7)',
  skeletonBackground: isDarkMode ? '#2A2A2A' : '#E0E0E0',
});

export const getStyles = (isDarkMode: boolean) => {
  const COLORS = getColors(isDarkMode);

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
    content: {
      flex: 1,
    },
    gradientBackground: {
      flex: 1,
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT,
      backgroundColor: COLORS.background,
    },
    flashListContainer: {
      height: 400,
      width: '100%',
    },
    noBadgesContainer: {
      height: 200,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDarkMode
        ? 'rgba(30, 30, 46, 0.6)'
        : 'rgba(255, 255, 255, 0.6)',
      borderRadius: 15,
      marginHorizontal: 20,
    },
    noBadgesText: {
      color: COLORS.textPrimary,
      fontSize: 18,
      textAlign: 'center',
      fontWeight: '600',
    },
    headerBlur: {
      ...StyleSheet.absoluteFillObject,
      top: 0,
      left: 0,
      right: 0,
      height: 100,
      zIndex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'ios' ? 50 : 20,
      height: 100,
      backgroundColor: COLORS.cardBackground,
    },
    backButton: {
      padding: 10,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: COLORS.textPrimary,
      textAlign: 'center',
      marginVertical: 10,
    },
    scrollViewContent: {
      flexGrow: 1,
      paddingBottom: 40,
    },
    profileSection: {
      flexDirection: 'column',
      alignItems: 'center',
      padding: 20,
      backgroundColor: COLORS.cardBackground,
      marginHorizontal: 20,
      borderRadius: 15,
      marginTop: 120,
      elevation: 8,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
    },
    profileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'space-between',
      marginBottom: 20,
    },
    profileImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
      borderWidth: 3,
      borderColor: COLORS.primary,
    },
    profileActiveDays: {
      fontSize: 16,
      color: COLORS.textSecondary,
      marginHorizontal: 10,
      flex: 1,
      textAlign: 'center',
    },
    scoreContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.primary,
      borderRadius: 40,
      width: 80,
      height: 80,
      elevation: 5,
      shadowColor: COLORS.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 5,
    },
    scoreText: {
      fontSize: 24,
      fontWeight: 'bold',
      color: COLORS.white,
    },
    pinnedBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'center',
    },
    pinnedBadgeLabel: {
      fontSize: 18,
      fontWeight: '600',
      color: COLORS.textPrimary,
      marginRight: 10,
    },
    pinnedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    pinnedBadgeImage: {
      width: 30,
      height: 30,
    },
    pinnedBadgeName: {
      fontSize: 18,
      color: COLORS.textPrimary,
      marginLeft: 10,
      fontWeight: '600',
    },
    sectionTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: isDarkMode ? COLORS.primary : COLORS.textPrimary,
      marginHorizontal: 20,
      marginTop: 30,
      marginBottom: 15,
    },
    badgeList: {
      paddingHorizontal: CARD_MARGIN / 2,
    },
    badgeContainer: {
      margin: CARD_MARGIN / 2,
      width: CARD_WIDTH,
      aspectRatio: 1,
    },
    badgeCard: {
      width: '100%',
      height: '100%',
      backgroundColor: COLORS.badgeBackground,
      borderRadius: 12,
      padding: 6,
      alignItems: 'center',
      justifyContent: 'space-between',
      elevation: 3,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      backfaceVisibility: 'hidden',
    },
    badgeIconContainer: {
      width: '80%',
      aspectRatio: 1,
      borderRadius: 100,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.cardBackground,
    },
    badgeImage: {
      width: '80%',
      height: '80%',
      marginVertical: -20,
    },
    badgeTitle: {
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      color: COLORS.textPrimary,
      marginBottom: 5,
    },
    badgeDescription: {
      fontSize: 10,
      textAlign: 'center',
      color: COLORS.textSecondary,
      marginBottom: 4,
    },
    progressSection: {
      width: '100%',
      alignItems: 'center',
    },
    progressText: {
      marginTop: 5,
      fontSize: 12,
      fontWeight: '500',
      color: COLORS.textPrimary,
    },
    lockOverlay: {
      position: 'absolute',
      top: 10,
      right: 10,
      backgroundColor: 'rgba(255,77,77,0.8)',
      borderRadius: 20,
      padding: 8,
    },
    badgeBackCard: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: COLORS.badgeBackground,
      borderRadius: 12,
      padding: 10,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 3,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      backfaceVisibility: 'hidden',
      transform: [{ rotateY: '180deg' }],
    },
    badgeBackTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: COLORS.textPrimary,
      marginBottom: 10,
      textAlign: 'center',
    },
    badgeDetails: {
      fontSize: 14,
      textAlign: 'center',
      color: COLORS.textPrimary,
      marginBottom: 5,
    },
    unearnedBadge: {
      opacity: 0.2,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: COLORS.background,
    },
    loadingText: {
      marginTop: 15,
      fontSize: 18,
      fontWeight: '500',
      color: COLORS.textPrimary,
    },
    badgeTableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.cardBackground,
      padding: 15,
      marginHorizontal: 20,
      borderRadius: 15,
      marginBottom: 15,
      elevation: 4,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    },
    badgeImageContainer: {
      position: 'relative',
      width: 80,
      height: 80,
      justifyContent: 'center',
      alignItems: 'center',
    },
    badgeTableImage: {
      width: 70,
      height: 70,
      opacity: 0.5,
    },
    badgeOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: COLORS.overlayBackground,
      borderRadius: 40,
    },
    lockIcon: {
      position: 'absolute',
    },
    badgeTableInfo: {
      marginLeft: 20,
      flex: 1,
    },
    badgeTableTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: COLORS.textPrimary,
    },
    badgeTableDescription: {
      fontSize: 14,
      color: COLORS.textSecondary,
    },
    badgeTableProgressText: {
      fontSize: 14,
      color: COLORS.textPrimary,
      marginTop: 8,
      fontWeight: '600',
    },

    // Skeleton styles
    skeletonBackButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonHeaderTitle: {
      width: 150,
      height: 30,
      borderRadius: 15,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonTrophy: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonProfileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 20,
      backgroundColor: COLORS.cardBackground,
      marginHorizontal: 20,
      borderRadius: 15,
      marginTop: 120,
    },
    skeletonProfileImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonProfileInfo: {
      flex: 1,
      marginLeft: 20,
      height: 60,
      borderRadius: 8,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonSectionTitle: {
      width: 150,
      height: 30,
      borderRadius: 15,
      backgroundColor: COLORS.skeletonBackground,
      marginHorizontal: 20,
      marginTop: 30,
      marginBottom: 15,
    },
    skeletonBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.cardBackground,
      padding: 15,
      marginHorizontal: 20,
      borderRadius: 15,
      marginBottom: 15,
    },
    skeletonBadgeImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonBadgeInfo: {
      flex: 1,
      marginLeft: 20,
    },
    skeletonBadgeTitle: {
      width: '60%',
      height: 20,
      borderRadius: 10,
      backgroundColor: COLORS.skeletonBackground,
      marginBottom: 10,
    },
    skeletonBadgeDescription: {
      width: '80%',
      height: 15,
      borderRadius: 8,
      backgroundColor: COLORS.skeletonBackground,
      marginBottom: 10,
    },
    skeletonProgressBar: {
      width: '100%',
      height: 8,
      borderRadius: 4,
      backgroundColor: COLORS.skeletonBackground,
    },
  });
};
