import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const getColors = (isDarkMode: boolean) => ({
  primary: '#39FF14', // Bright green
  secondary: '#50E3C2',
  background: isDarkMode ? '#151515' : '#8C8C8C', // Light gray instead of pure white
  cardBackground: isDarkMode ? '#1E1E1E' : '#E0E0E0', // Slightly darker gray for cards in light mode
  white: '#FFFFFF',
  black: '#000000',
  textPrimary: isDarkMode ? '#FFFFFF' : '#000000', // Black text in light mode
  textSecondary: isDarkMode ? '#B0B0C0' : '#333333', // Dark gray text in light mode
  gold: '#FFD700',
  lightGray: '#E0E0E0',
  darkGray: '#2A2A2A',
  error: '#FF4D4D',
  success: '#4CAF50',
  particlesDark: '#39FF14',
  particlesLight: '#707070', // Darker gray for particles in light mode for better visibility
  badgeBackground: isDarkMode ? '#1E1E2E' : '#F8F8F8', // Lighter gray for badge background in light mode
  overlayBackground: 'rgba(0, 0, 0, 0.7)',
  skeletonBackground: isDarkMode ? '#2A2A2A' : '#D3D3D3', // Adjusted for light mode
});

export const getStyles = (isDarkMode: boolean) => {
  const COLORS = getColors(isDarkMode);

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: COLORS.background,
    },
    content: {
      flex: 1,
    },
    gradientBackground: {
      flex: 1,
      width: SCREEN_WIDTH,
      height: SCREEN_HEIGHT,
      backgroundColor: COLORS.background,
    },
    lightBackground: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: COLORS.background,
    },
    badgeTableRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.cardBackground,
      padding: 15,
      marginHorizontal: 20,
      borderRadius: 15,
      marginBottom: 15,
      elevation: 4,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      borderWidth: isDarkMode ? 0 : 2,
      borderColor: isDarkMode ? 'transparent' : COLORS.primary,
    },
    badgeImageContainer: {
      position: 'relative',
      width: 80,
      height: 80,
      justifyContent: 'center',
      alignItems: 'center',
    },
    badgeTableImage: {
      width: 70,
      height: 70,
      opacity: 0.9,
    },
    badgeOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: COLORS.overlayBackground,
      borderRadius: 40,
    },
    lockIcon: {
      position: 'absolute',
    },
    badgeTableInfo: {
      marginLeft: 20,
      flex: 1,
    },
    badgeTableTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: COLORS.textPrimary,
    },
    badgeTableDescription: {
      fontSize: 14,
      color: COLORS.textSecondary,
    },
    badgeProgressContainer: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    badgeProgressBar: {
      flex: 1,
      marginRight: 10,
    },
    badgeTableProgressText: {
      fontSize: 14,
      color: COLORS.textPrimary,
      fontWeight: '600',
    },
    headerBlur: {
      ...StyleSheet.absoluteFillObject,
      top: 0,
      left: 0,
      right: 0,
      height: 100,
      zIndex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingTop: Platform.OS === 'ios' ? 20 : 60,
      height: 120,
      backgroundColor: COLORS.cardBackground,
    },
    backButton: {
      padding: 10,
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: 'bold',
      color: COLORS.textPrimary,
      textAlign: 'center',
      marginVertical: 10,
    },
    profileSection: {
      flexDirection: 'column',
      alignItems: 'center',
      padding: 20,
      backgroundColor: COLORS.cardBackground,
      marginHorizontal: 20,
      borderRadius: 15,
      marginTop: 140,
      elevation: 8,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
    },
    profileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'center',
      marginBottom: 20,
    },
    profileImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
      borderWidth: 3,
      borderColor: COLORS.primary,
    },
    profileActiveDays: {
      fontSize: 16,
      color: COLORS.textSecondary,
      marginHorizontal: 10,
      textAlign: 'center',
    },
    progressContainer: {
      width: '100%',
      marginTop: 10,
      alignItems: 'center',
    },
    progressBar: {
      width: '80%',
      marginTop: 5,
    },
    progressText: {
      fontSize: 16,
      color: COLORS.textPrimary,
      fontWeight: '600',
    },
    pinnedBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      justifyContent: 'center',
      marginTop: 10,
    },
    pinnedBadgeLabel: {
      fontSize: 18,
      fontWeight: '600',
      color: COLORS.textPrimary,
      marginRight: 10,
    },
    pinnedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    pinnedBadgeImage: {
      width: 30,
      height: 30,
    },
    pinnedBadgeName: {
      fontSize: 18,
      color: COLORS.textPrimary,
      marginLeft: 10,
      fontWeight: '600',
    },
    sectionTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: COLORS.primary,
      marginHorizontal: 20,
      marginTop: 30,
      marginBottom: 15,
    },
    earnedBadgesContainer: {
      paddingHorizontal: 10,
    },
    earnedBadgeContainer: {
      margin: 5,
      width: (SCREEN_WIDTH - 50) / 3,
      alignItems: 'center',
      flexDirection: 'column',
    },
    badgeCard: {
      width: 120,
      height: 120,
      backgroundColor: COLORS.badgeBackground,
      borderRadius: 12,
      padding: 5,
      alignItems: 'center',
      justifyContent: 'space-between',
      elevation: 3,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      backfaceVisibility: 'hidden',
      borderWidth: isDarkMode ? 0 : 2,
      borderColor: isDarkMode ? 'transparent' : COLORS.primary,
    },
    badgeIconContainer: {
      width: '80%',
      aspectRatio: 1,
      borderRadius: 100,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.cardBackground,
    },
    badgeImage: {
      width: '80%',
      height: '80%',
    },
    badgeTitle: {
      fontSize: 12,
      fontWeight: '600',
      textAlign: 'center',
      color: COLORS.textPrimary,
      marginBottom: 5,
    },
    lockOverlay: {
      position: 'absolute',
      top: 10,
      right: 10,
      backgroundColor: 'rgba(255,77,77,0.8)',
      borderRadius: 20,
      padding: 4,
    },
    badgeBackCard: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: COLORS.badgeBackground,
      borderRadius: 12,
      padding: 10,
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 3,
      shadowColor: isDarkMode ? COLORS.white : COLORS.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      backfaceVisibility: 'hidden',
      transform: [{ rotateY: '180deg' }],
      borderWidth: isDarkMode ? 0 : 2,
      borderColor: isDarkMode ? 'transparent' : COLORS.primary,
    },
    badgeBackTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: COLORS.textPrimary,
      marginBottom: 5,
      textAlign: 'center',
    },
    badgeDetails: {
      fontSize: 12,
      textAlign: 'center',
      color: COLORS.textSecondary,
      marginBottom: 5,
    },
    // Skeleton styles
    skeletonBackButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonHeaderTitle: {
      width: 150,
      height: 30,
      borderRadius: 15,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonTrophy: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonProfileSection: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 20,
      backgroundColor: COLORS.cardBackground,
      marginHorizontal: 20,
      borderRadius: 15,
      marginTop: 120,
    },
    skeletonProfileImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonProfileInfo: {
      flex: 1,
      marginLeft: 20,
      height: 60,
      borderRadius: 8,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonSectionTitle: {
      width: 150,
      height: 30,
      borderRadius: 15,
      backgroundColor: COLORS.skeletonBackground,
      marginHorizontal: 20,
      marginTop: 30,
      marginBottom: 15,
    },
    skeletonBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.cardBackground,
      padding: 15,
      marginHorizontal: 20,
      borderRadius: 15,
      marginBottom: 15,
    },
    skeletonBadgeImage: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: COLORS.skeletonBackground,
    },
    skeletonBadgeInfo: {
      flex: 1,
      marginLeft: 20,
    },
    skeletonBadgeTitle: {
      width: '60%',
      height: 20,
      borderRadius: 10,
      backgroundColor: COLORS.skeletonBackground,
      marginBottom: 10,
    },
    skeletonBadgeDescription: {
      width: '80%',
      height: 15,
      borderRadius: 8,
      backgroundColor: COLORS.skeletonBackground,
      marginBottom: 10,
    },
    skeletonProgressBar: {
      width: '100%',
      height: 8,
      borderRadius: 4,
      backgroundColor: COLORS.skeletonBackground,
    },
  });
};