import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  formContainer: {
    marginTop: -30,
    paddingVertical: 10,
    borderRadius: 20,
    width: '100%',
    paddingHorizontal: 2,
    alignSelf: 'center',
  },
  signupHeader: {
    fontSize: 35,
    fontWeight: 'bold',
    color: 'white',
    alignSelf: 'center',
    paddingVertical: 20,
  },
  errorMessage: {
    color: '#ff4d4d',
    fontSize: 14,
    paddingVertical: 10,
  },
  termsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  termsText: {
    color: '#BDBDBD',
    fontSize: 14,
    textAlign: 'center',
    marginVertical: 10,
  },
  termsHighlight: {
    color: '#1bd40b',
  },
  button2: {
    width: '100%',
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#00ff00',
    backgroundColor: 'transparent',
    alignItems: 'center',
    marginVertical: 10,
    alignSelf: 'center',
    paddingHorizontal: 60,
    justifyContent: 'center',
  },
  buttonText: {
    color: '#00ff00',
    fontSize: 16,
    fontWeight: 'bold',
  },
  toggleFormText: {
    color: '#007AFF',
    fontSize: 18,
    textAlign: 'center',
    marginVertical: 10,
    textDecorationLine: 'underline',
  },
  continueButtonsContainer: {
    width: '100%',
    alignSelf: 'center',
    marginBottom: 30,
    marginTop: 50,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#DADCE0',
  },
  googleButtonText: {
    color: '#757575',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 10,
  },
  buttonIcon: {
    marginRight: 10,
  },
  appleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000000',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  appleButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 10,
  },
  blurView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    borderRadius: 20,
    bottom: 0,
    zIndex: 1000,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
  },
  loadingText: {
    color: '#00ff00',
    marginTop: 10,
  },
});
